## A pair of functions to calculate and cache the inverse of a matrix

## A function that makes a special matrix that will store (cache) the 
## the matrix inverse (as generated by solve) one it is calculated.

makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL
  set <- function(y){
    x <<- y
    inv <<-NULL
  }
  get <- function() x
  setinv <- function(inverse) inv<<-inverse
  getinv <- function() inv
  
  list(set = set, get = get, setinv = setinv, getinv = getinv)
}


## cacheSolve checkes to see if the inverse of the matrix x
## has been cached. If not, solve(x) calculates the inverse 
## and caches the resulting inverse.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  ## check if x has cached inverse
  inv <- x$getinv()
  if(!is.null(inv)){
    message('getting cached data')
    return(inv)
  }
  mat <- x$get()
  inv <- solve(mat,...)
  x$setinv(inv)
  inv
}
